@startuml
hide empty description

[*] --> Начало_программы

Начало_программы --> Загрузка_данных: Начало программы
Загрузка_данных --> Проверка_сохраненных_данных: Данные загружены
Проверка_сохраненных_данных --> Оповещение: Сохраненные данные найдены
Проверка_сохраненных_данных --> Ввод_персональных_данных: Сохраненные данные не найдены
Оповещение --> Меню_выбора_операции: Оповещение выведено
Ввод_персональных_данных --> Создание_объекта_programmer: Ввод завершен
Создание_объекта_programmer --> Ввод_настроек_языка_программирования: Ввод настроек
Ввод_настроек_языка_программирования --> Создание_объекта_programming_language: Ввод завершен
Создание_объекта_programming_language --> Написание_исходного_кода: Ввод исходного кода
Написание_исходного_кода --> Меню_выбора_операции: Вывод списка операций
Меню_выбора_операции --> Сохранение_изменений_программы : Ввод операции компиляции
Сохранение_изменений_программы --> Компиляция : Изменения сохранены
Компиляция --> Вывод_результата : Проект скомпилирован
Вывод_результата --> Завершение_программы : Результат выведен
Завершение_программы --> [*] : Программа завершена

state Ввод_персональных_данных {
 [*] --> Ввод_ФИО_программиста

 Ввод_ФИО_программиста --> Ввод_возраста_программиста: Ввод ФИО завершен
 Ввод_возраста_программиста --> Ввод_опыта_работы: Ввод возраста завершен
 Ввод_опыта_работы --> Проверка_введённых_данных: Ввод опыта работы завершен
 Проверка_введённых_данных --> Ввод_персональных_данных: Возраст или ФИО введены некорректно
 Проверка_введённых_данных --> Присвоение_введенных_данных: Данные введены корректно
 Присвоение_введенных_данных --> Передача_данных: Данные присвоены
 Передача_данных --> [*]: Данные переданы
}

state Ввод_настроек_языка_программирования {
 [*] --> Ввод_названия_языка_программирования

 Ввод_названия_языка_программирования --> Ввод_ключевых_слов: Название введено
 Ввод_ключевых_слов --> Ввод_расширения_файла: Ключевые слова введены
 Ввод_расширения_файла --> Присвоение_настроек_языка: Расширение файла введено
 Присвоение_настроек_языка --> Передача_данных_о_языке: Данные присвоены
 Передача_данных_о_языке --> [*]: Данные переданы
}

state Ввод_ключевых_слов {
 [*] --> Ожидание_ввода_ключевого_слова

 Ожидание_ввода_ключевого_слова --> Проверка_введенного_ключевого_слова: Ввод завершен
 Проверка_введенного_ключевого_слова --> Ожидание_ввода_ключевого_слова: Ключевое слово состоит из нескольких слов
 Проверка_введенного_ключевого_слова --> Меню_выбора_категории: Ключевое слово корректно
 Меню_выбора_категории --> Ввод_категории: Вывод доступных категорий
 Ввод_категории --> Проверка_введённой_категории: Ввод завершен
 Проверка_введённой_категории --> Меню_выбора: Данные введены некорректно
 Проверка_введённой_категории --> Сохранение_введённых_данных: Данные введены корректно
 Сохранение_введённых_данных --> Меню_выбора: Выбор следующего действия
 Меню_выбора --> Ожидание_ввода_ключевого_слова: Добавление нового ключевого слова
 Меню_выбора --> Передача_ключевых_слов: Закончить ввод
 Передача_ключевых_слов --> [*]: Ключевые слова переданы
}

state Написание_исходного_кода {
 [*] --> Меню_выбора_следующего_действия

 Меню_выбора_следующего_действия --> Добавление_строки_исходного_кода : Строка введена
 Меню_выбора_следующего_действия --> Сохранение_исходного_кода : Сохранить код
 Добавление_строки_исходного_кода --> Меню_выбора_следующего_действия : Строка введена
 Сохранение_исходного_кода --> Ввод_описания_кода : Код сохранен
 Ввод_описания_кода --> Ввод_расширения_файла_исходного_кода : Описание введено
 Ввод_расширения_файла_исходного_кода --> Сохранение_изменений : Расширение введено
 Сохранение_изменений --> Передача_исходного_кода : Изменения сохранены
 Передача_исходного_кода --> [*] : Код передан
}

state Перезаписать_исходный_код {
 [*] --> Ожидание_следующего_действия

 Ожидание_следующего_действия --> Добавление_строки_кода : Строка введена
 Ожидание_следующего_действия --> Сохранение_измененного_кода : Сохранить код
 Добавление_строки_кода --> Ожидание_следующего_действия : Строка введена
 Сохранение_измененного_кода --> Передача_изменённого_кода : Код сохранен
 Передача_изменённого_кода --> [*] : Код передан
}

state Меню_выбора_операции {
 [*] --> Вывод_списка_операций

 Вывод_списка_операций --> Выбор_операции : Список выведен
 Выбор_операции --> Написание_исходного_кода : Перезаписать проект
 Выбор_операции --> Перезаписать_исходный_код : Перезаписать исходный код
 Выбор_операции --> Перезаписать_описание : Перезаписать описание
 Выбор_операции --> Ввод_персональных_данных : Перезаписать данные программиста
 Выбор_операции --> Ввод_настроек_языка_программирования : Перезаписать настройки языка
 Выбор_операции --> Выход_из_меню_выбора : Перейти к компиляции
 Перезаписать_описание --> Ввод_описания : Ожидание ввода описания
 Ввод_описания --> Сохранение_описания : Описание введено
 Сохранение_описания --> Вывод_списка_операций : Описание сохранено
 Выход_из_меню_выбора --> [*] : Выход завершен
}

Ожидание_начала_смены --> Завершение_программы: Нажата кнопка "N"
Завершение_программы --> [*]: Программа завершена
@enduml