@startuml
'https://plantuml.com/class-diagram
title Состояния программы

[*] --> Начало_программы
Начало_программы --> Загрузка_данных: Начало программы
Загрузка_данных --> Проверка_сохраненных_данных: Данные загружены
Проверка_сохраненных_данных --> Вывод_меню: Сохраненные данные найдены
Проверка_сохраненных_данных --> Создание_социальной_сети: Сохраненные данные не найдены
Вывод_меню --> Добавление_пользователя: Выбран 1ый пункт меню
Вывод_меню --> Добавление_новости: Выбран 2ой пункт меню
Вывод_меню --> Добавление_друга: Выбран 3ий пункт меню
Вывод_меню --> Добавление_группы: Выбран 4ый пункт меню
Вывод_меню --> Добавление_пользователя_в_группу: Выбран 5ый пункт меню
Вывод_меню --> Просмотр_пользователей: Выбран 6ой пункт меню
Вывод_меню --> Просмотр_новостей: Выбран 7ой пункт меню
Вывод_меню --> Просмотр_сообщений: Выбран 8ой пункт меню
Вывод_меню --> Просмотр_всех_групп: Выбран 9ый пункт меню
Вывод_меню --> Написание_сообщения: Выбран 10ый пункт меню
Вывод_меню --> Удаление_из_друзей: Выбран 11ый пункт меню

Добавление_пользователя --> Сохранение_состояния: Пользователь добавлен
Добавление_новости --> Сохранение_состояния: Новость добавлена
Добавление_друга --> Сохранение_состояния: Друг добавлен
Добавление_группы --> Сохранение_состояния: Группа добавлена
Добавление_пользователя_в_группу --> Сохранение_состояния: Пользователь добавлен в группу
Просмотр_пользователей --> Завершение_программы
Просмотр_новостей --> Завершение_программы
Просмотр_сообщений --> Завершение_программы
Просмотр_всех_групп --> Завершение_программы
Написание_сообщения --> Сохранение_состояния: Сообщение написано
Удаление_из_друзей --> Сохранение_состояния: Друг удален
Создание_социальной_сети --> Завершение_программы: Социальная сеть создана
Сохранение_состояния --> Завершение_программы: Состояние сохранено

Завершение_программы --> [*]

state Добавление_пользователя {
    [*] --> Ввод_возраста_пользователя_для_добавления
    Ввод_псевдонима_пользователя_для_добавления --> Ввод_псевдонима_пользователя_для_добавления: Введен занятый псевдоним
    Ввод_псевдонима_пользователя_для_добавления --> Ввод_имени_пользователя_для_добавления: Введен незанятый псевдоним
    Ввод_имени_пользователя_для_добавления --> Ввод_фамилии_пользователя_для_добавления: Имя пользователя введено
    Ввод_фамилии_пользователя_для_добавления --> Ввод_возраста_пользователя_для_добавления: Фамилия пользователя введена
    Ввод_возраста_пользователя_для_добавления --> Ввод_пола_пользователя_для_добавления: Введен корректный возраст пользователя
    Ввод_возраста_пользователя_для_добавления --> [*]: Введен некорректный возраст пользователя
    Ввод_пола_пользователя_для_добавления --> Создание_пользователя: Введен корректный пол пользователя
    Ввод_пола_пользователя_для_добавления --> [*]: Введен некорректный пол пользователя
    Создание_пользователя --> Добавление_пользователя_в_базу: Пользователь создан
    Добавление_пользователя_в_базу --> [*]
}

state Добавление_новости {
    [*] --> Ввод_псевдонима_пользователя_для_публикации
    Ввод_псевдонима_пользователя_для_публикации --> Получение_пользователя_для_публикации_по_псевдониму: Введен существующий псевдоним пользователя
    Ввод_псевдонима_пользователя_для_публикации --> Ввод_псевдонима_пользователя_для_публикации: Введен несуществующий псевдоним пользователя
    Получение_пользователя_для_публикации_по_псевдониму --> Ввод_контента_новости_для_добавления: Пользователь получен
    Ввод_контента_новости_для_добавления --> Вывод_вопроса_о_желании_пользователя_добавить_изображение_к_новости: Введен контент для новости
    Вывод_вопроса_о_желании_пользователя_добавить_изображение_к_новости --> Добавление_изображения_к_новости: Выбран 1ый пункт
    Вывод_вопроса_о_желании_пользователя_добавить_изображение_к_новости --> Создание_новости: Выбран 2ой пункт
    Создание_новости --> Добавление_новости_в_базу: Новость создана
    Добавление_новости_в_базу --> [*]
}

state Добавление_изображения_к_новости {
    [*] --> Ввод_контента_изображения
    Ввод_контента_изображения --> Ввод_высоты_изображения: Введен контент для изображения
    Ввод_высоты_изображения --> Ввод_ширины_изображения: Введена корректная высота изображения
    Ввод_высоты_изображения --> [*]: Введена некорректная высота изображения
    Ввод_ширины_изображения --> Создание_изображения: Введена корректная ширина изображения
    Ввод_ширины_изображения --> [*]: Введена некорректная ширина изображения
}

state Добавление_друга {
    [*] --> Ввод_псевдонима_пользователя_для_добавления_друга
    Ввод_псевдонима_пользователя_для_добавления_друга --> Получение_пользователя_для_добавления_друга_по_всевдониму: Введен сущесвующий псевдоним пользователя
    Ввод_псевдонима_пользователя_для_добавления_друга --> Ввод_псевдонима_пользователя_для_добавления_друга: Введен несуществующий псевдоним пользователя
    Получение_пользователя_для_добавления_друга_по_всевдониму --> Ввод_псевдонима_друга: Пользователь получен
    Ввод_псевдонима_друга --> Получение_друга_по_псевдониму: Введен существующий псевдоним пользователя
    Ввод_псевдонима_друга --> Ввод_псевдонима_друга: Введен несушествующий псевдоним пользователя
    Получение_друга_по_псевдониму --> Добавление_пользователю_друга: Друг получен
    Добавление_пользователю_друга --> Добавление_другу_пользователя_в_качестве_друга: Пользователь добавил друга
    Добавление_другу_пользователя_в_качестве_друга --> [*]: Друг добавил пользователя в качестве друга
}

state Добавление_группы {
    [*] --> Ввод_названия_группы_для_добавления
    Ввод_названия_группы_для_добавления --> Создание_группы: Введено несуществующее название группы
    Ввод_названия_группы_для_добавления --> Ввод_названия_группы_для_добавления: Введено существующее название группы
    Создание_группы --> Добавление_группы_в_базу: Группа создана
    Добавление_группы_в_базу --> [*]
}

state Добавление_пользователя_в_группу {
    [*] --> Ввод_псевдонима_пользователя_для_добавления_в_группу
    Ввод_псевдонима_пользователя_для_добавления_в_группу --> Получение_пользователя_для_добавления_в_группу: Введен существующий псевдоним пользователя
    Ввод_псевдонима_пользователя_для_добавления_в_группу --> Ввод_псевдонима_пользователя_для_добавления_в_группу: Введен несуществующий псевдоним пользователя
    Получение_пользователя_для_добавления_в_группу --> Ввод_названия_группы_для_добавления_пользователя: Пользователь получен
    Ввод_названия_группы_для_добавления_пользователя --> Получение_группы_для_добавления_пользователя: Введено существующее название группы
    Ввод_названия_группы_для_добавления_пользователя --> Ввод_названия_группы_для_добавления_пользователя: Введено несуществующее название группы
    Получение_группы_для_добавления_пользователя --> Добавление_пользователю_группу: Группа получена
    Добавление_пользователю_группу --> Добавление_группе_пользователя: Пользователь добавил группу
    Добавление_группе_пользователя --> [*]: Группа добавила пользователя
}

state Просмотр_сообщений {
    [*] --> Ввод_пользователя_для_просмотра_сообщений
    Ввод_пользователя_для_просмотра_сообщений --> Получение_пользователя_для_просмотра_сообщений: Введен существующий псевдоним пользователя
    Ввод_пользователя_для_просмотра_сообщений --> Ввод_пользователя_для_просмотра_сообщений: Введен несуществующий псевдоним пользователя
    Получение_пользователя_для_просмотра_сообщений --> Вывод_отправленных_сообщений_пользователя: Пользователь получен
    Вывод_отправленных_сообщений_пользователя --> Вывод_полученных_сообщений_пользователя: Были выведены отправленные сообщения пользователя
    Вывод_полученных_сообщений_пользователя --> [*]: Были выведены полученные сообщения пользователя
}

state Просмотр_пользователей {
    [*] --> Вывод_всех_пользователей
    Вывод_всех_пользователей --> [*]: Выведены все пользователи
}

state Просмотр_всех_групп {
    [*] --> Вывод_всех_групп
    Вывод_всех_групп --> [*]: Выведены все группы
}

state Просмотр_новостей {
    [*] --> Вывод_всех_новостей
    Вывод_всех_новостей --> [*]: Выведены все новости
}

state Написание_сообщения {
    [*] --> Ввод_псевдонима_отправляющего_пользователя
    Ввод_псевдонима_отправляющего_пользователя --> Получение_отправляющего_пользователя: Введен существующий псевдоним пользователя
    Ввод_псевдонима_отправляющего_пользователя --> Ввод_псевдонима_отправляющего_пользователя: Введен несуществующий псевдоним пользователя
    Получение_отправляющего_пользователя --> Ввод_псевдонима_принимающего_пользователя: Получен отправляющий пользователь
    Ввод_псевдонима_принимающего_пользователя --> Получение_принимающего_пользователя: Введен существующий псевдоним пользователя
    Ввод_псевдонима_принимающего_пользователя --> Ввод_псевдонима_принимающего_пользователя: Введен несуществующий псевдоним пользователя
    Получение_принимающего_пользователя --> Ввод_контента_сообщения: Получени принимающий пользователь
    Ввод_контента_сообщения --> Создание_сообщения: Введен контент сообщения
    Создание_сообщения --> Добавление_сообщения_в_качестве_полученного_получателю: Сообщение создано
    Добавление_сообщения_в_качестве_полученного_получателю --> Добавление_сообщения_в_качестве_отправленного_отправителю: Сообщение добавлено в качестве полученного получателю
    Добавление_сообщения_в_качестве_отправленного_отправителю --> [*]: Сообщение добавлено в качестве отправленного отправителю
}

state Удаление_из_друзей {
    [*] --> Ввод_псевдонима_пользователя_для_удаления_друга
    Ввод_псевдонима_пользователя_для_удаления_друга --> Получение_пользователя_для_удаления_друга: Введен сущесвующий псевдоним пользователя
    Ввод_псевдонима_пользователя_для_удаления_друга --> Ввод_псевдонима_пользователя_для_удаления_друга: Введен несуществующий псевдоним пользователя
    Получение_пользователя_для_удаления_друга --> Ввод_псевдонима_друга_для_удаления: Получен пользователь для удаления друга
    Ввод_псевдонима_друга_для_удаления --> Удаление_друга_из_друзей_пользователя: Введен сущесвующий псевдоним пользователя
    Ввод_псевдонима_друга_для_удаления --> Ввод_псевдонима_друга_для_удаления: Введен несуществующий псевдоним пользователя
    Удаление_друга_из_друзей_пользователя --> Удаление_пользователя_из_друзей_друга: Удален друг из друзей пользвателя
    Удаление_пользователя_из_друзей_друга --> [*]: Удален пользователь из друзей друга
}



@enduml