@startuml
title Состояния программы

[*] --> Начало_программы
Начало_программы --> Загрузка_данных: Начало программы
Загрузка_данных --> Вывод_меню
Вывод_меню --> Добавление_номера: Выбран 1ый пункт меню
Вывод_меню --> Показать_свободные_номера: Выбран 2ой пункт меню
Вывод_меню --> Показать_все_номера: Выбран 3ий пункт меню
Вывод_меню --> Добавление_работника: Выбран 4ый пункт меню
Вывод_меню --> Показать_свободных_работников: Выбран 5ый пункт меню
Вывод_меню --> Показать_всех_работников: Выбран 6ой пункт меню
Вывод_меню --> Уволить_работника: Выбран 7ой пункт меню
Вывод_меню --> Забронировать_номер: Выбран 8ой пункт меню
Вывод_меню --> Оплата_и_выселение_из_номера: Выбран 9ый пункт меню
Вывод_меню --> Заказать_сервисную_услугу: Выбран 10ый пункт меню
Вывод_меню --> Обслуживание_в_ресторане: Выбран 11ый пункт меню
Вывод_меню --> Показать_невыполненные_услуги: Выбран 12ый пункт меню
Вывод_меню --> Завершить_услугу: Выбран 13ый пункт меню
Вывод_меню --> Показать_всех_гостей: Выбран 14ый пункт меню
Вывод_меню --> Показать_все_брони: Выбран 15ый пункт меню
Вывод_меню --> Заверешение_программы: Выбран неккоректный пункт

Добавление_номера  --> Вывод_меню: Номер добавлен
Показать_свободные_номера --> Вывод_меню
Показать_все_номера --> Вывод_меню
Добавление_работника --> Вывод_меню: Работник добавлен
Показать_свободных_работников --> Вывод_меню
Показать_всех_работников --> Вывод_меню
Уволить_работника --> Вывод_меню: Работник уволен
Забронировать_номер --> Вывод_меню: Номер забронирован
Оплата_и_выселение_из_номера --> Вывод_меню: Гость выселен из номера
Заказать_сервисную_услугу --> Вывод_меню: Сервисная услуга добавлена в список невыполненных
Обслуживание_в_ресторане --> Вывод_меню: Услуга добавлена в список невыполненных услуг
Показать_невыполненные_услуги --> Вывод_меню
Завершить_услугу --> Вывод_меню: Услуга завершена
Показать_всех_гостей --> Вывод_меню
Показать_все_брони --> Вывод_меню
Заверешение_программы --> Сохранение_состояния: Состояние сохранено

Сохранение_состояния --> [*]

state Добавление_номера{
    [*] --> Ввод_номера_комнаты
    Ввод_номера_комнаты --> Вывод_ошибки: Введён уже существующий номер
    Ввод_номера_комнаты --> Ввод_типа_комнаты
    Ввод_типа_комнаты --> Вывод_ошибки: Введён несуществующий тип
    Ввод_типа_комнаты --> Создание_комнаты
    Вывод_ошибки --> меню
    Создание_комнаты --> Добавление_комнаты_в_список_комнат
    Добавление_комнаты_в_список_комнат --> [*] : Комната добавлена
}

state Показать_свободные_номера{
    [*] --> Вывод_номеров_со_свободным_статусом
    Вывод_номеров_со_свободным_статусом --> [*] : Все свободные номера выведены
}

state Показать_все_номера{
    [*] --> Вывод_всех_номеров
    Вывод_всех_номеров --> [*] : Все номера выведены
}

state Добавление_работника{
    [*] --> Ввод_имени_работника
    Ввод_имени_работника --> Ввод_возраста_работника
    Ввод_возраста_работника --> Вывод_ошибки: Введено_не_число
    Ввод_возраста_работника --> Ввод_паспорта_работника
    Ввод_паспорта_работника --> Вывод_ошибки: Работник с таким паспортом уже существует
    Вывод_ошибки --> Вывод_меню
    Ввод_паспорта_работника --> Создание_работника
    Создание_работника --> Добавление_работника_в_список_работников
}

state Показать_свободных_работников{
    [*] --> Вывод_всех_свободных_работников
    Вывод_всех_свободных_работников --> [*]: Все свободные работники выведены
}

state Показать_всех_работников{
    [*] --> Вывод_всех_работников
    Вывод_всех_работников --> [*]: Все работники выведены
}

state Уволить_работника{
    [*] --> Ввод_паспорта_работника
    Ввод_паспорта_работника --> Вывод_ошибки: Работника с таким паспортом нет
    Ввод_паспорта_работника --> Вывод_ошибки: Работник с таким паспортом сейчас занят
    Ввод_паспорта_работника --> Удаление_работника_из_списка_работников
    Вывод_ошибки --> Вывод_меню
    Удаление_работника_из_списка_работников --> [*]: Работник уволен
}

state Забронировать_номер{
    [*] --> Ввод_имени_гостя
    Ввод_имени_гостя --> Ввод_возраста_гостя
    Ввод_возраста_гостя --> Ввод_паспорта_гостя
    Ввод_паспорта_гостя --> Ввод_номера_комнаты
    Ввод_номера_комнаты --> Ввод_количества_дней
    Ввод_количества_дней --> Поиск_гостя_в_списке_гостей
    Поиск_гостя_в_списке_гостей --> Гость_найден: Гость с таким паспортом есть в списке
    Поиск_гостя_в_списке_гостей --> Регистрация_гостя: Гостя с таким паспортом нет в списке
    Гость_найден --> Поиск_комнаты_с_введёным_номером
    Регистрация_гостя --> Поиск_комнаты_с_введёным_номером
    Поиск_комнаты_с_введёным_номером --> Вывод_ошибки: Комнаты с таким номером нет
    Поиск_комнаты_с_введёным_номером --> Создание_брони: Комнаты с таким номером есть
    Создание_брони --> Добавление_брони_в_список_броней
    Добавление_брони_в_список_броней --> [*]: Номер забронирован
}

state Оплата_и_выселение_из_номера{
    [*] --> Ввод_паспорта_гостя
    Ввод_паспорта_гостя --> Поиск_паспорта_в_списке_броней
    Поиск_паспорта_в_списке_броней --> Вывод_ошибки: Гостя с таким паспортом нет
    Поиск_паспорта_в_списке_броней --> Бронь_найдена: Бронь с паспортом гостя есть в списке
    Бронь_найдена --> Подсчёт_стоимости_проживания
    Подсчёт_стоимости_проживания --> Вывод_стоимости_проживания
    Вывод_стоимости_проживания --> Выселение_из_номера
    Выселение_из_номера --> [*]: Произведена оплата и выселение из номера
}

state Заказать_сервисную_услугу{
    [*] --> Ввод_паспорта_работника
    Ввод_паспорта_работника --> Ввод_паспорта_гостя
    Ввод_паспорта_гостя --> Ввод_типа_услуги
    Ввод_типа_услуги --> Вывод_ошибки: Работника или гостя или услуги не существует
    Вывод_ошибки --> Вывод_меню
    Ввод_типа_услуги --> Создание_услуги
    Создание_услуги --> Добавление_услуги_в_список_невыполненных_услуг
    Добавление_услуги_в_список_невыполненных_услуг --> [*]: Сервисная услуга заказана
}

state Обслуживание_в_ресторане{
    [*] --> Ввод_паспорта_работника
    Ввод_паспорта_работника --> Ввод_паспорта_гостя
    Ввод_паспорта_гостя --> Вывод_ошибки: Работника или гостя или услуги не существует/заняты
    Вывод_ошибки --> Вывод_меню
    Ввод_паспорта_гостя --> Создание_услуги
    Создание_услуги --> Добавление_услуги_в_список_невыполненных_услуг
    Добавление_услуги_в_список_невыполненных_услуг --> [*]: Услуга заказана
}

state Показать_невыполненные_услуги{
    [*] --> Вывод_невыполненных_услуг
    Вывод_невыполненных_услуг --> [*]: Услуги выведены
}

state Завершить_услугу{
    [*] --> Ввод_паспорта_работника
    Ввод_паспорта_работника --> Поиск_услуги_с_введёным_паспортом
    Поиск_услуги_с_введёным_паспортом --> Вывод_ошибки: Услуги с таким паспортом нет
    Поиск_услуги_с_введёным_паспортом --> Услуга_найдена: Услуга с таким паспортом существует
    Услуга_найдена --> Удаление_услуги_из_списка_невыполненных_услуг
    Удаление_услуги_из_списка_невыполненных_услуг --> [*]: Услуга завершена
}


state Показать_всех_гостей{
    [*] --> Вывод_всех_гостей
    Вывод_всех_гостей --> [*] : Все гости выведены
}

state Показать_все_брони{
    [*] --> Вывод_всех_броней
    Вывод_всех_броней --> [*] : Все брони_выведены
}


@enduml