@startuml
hide empty description

[*] --> Начало_программы

Начало_программы --> Загрузка_данных: Начало программы
Загрузка_данных --> Проверка_сохраненных_данных: Данные загружены
Проверка_сохраненных_данных --> Приветствие: Сохраненные данные найдены
Проверка_сохраненных_данных --> Ввод_информации: Сохраненные данные не найдены
Приветствие --> Завершение_приветствия: Приветствие выведено
Ввод_информации --> Создание_объекта_Police: Ввод завершен
Завершение_приветствия --> Ожидание_начала_смены: Приветствие завершено
Ожидание_начала_смены --> Подготовка_к_смене: Нажата кнопка "Y"
Ожидание_начала_смены --> Завершение_программы: Нажата любая другая кнопка

state Подготовка_к_смене {
 [*] --> Анализ_случаев

 Анализ_случаев --> Создание_объекта_Duty: Данные проанализированы
 Создание_объекта_Duty --> Генерация_мероприятий: Создан объект Duty
 Генерация_мероприятий --> Назначение_на_патрулирование: Мероприятия сгенерированы
 Назначение_на_патрулирование --> Назначение_детективов: Офицеры для патрулирования назначены
 Назначение_детективов --> Назначение_на_общественную_безопасность: Детективы назначены
 Назначение_на_общественную_безопасность --> Вывод_информации: Офицеры на общественную безопасность назначены
 Вывод_информации --> [*]: Информация выведена
}

state Смена_в_процессе {
 [*] --> Вход_в_смену

 Вход_в_смену --> Ответы_на_вызовы: Смена началась
 Ответы_на_вызовы --> Ответы_на_вызовы: Продолжение смены
 Ответы_на_вызовы --> Выход_из_смены: Смена завершена
 Выход_из_смены --> [*]: Смена закончена
}

Подготовка_к_смене --> Смена_в_процессе: Подготовка завершена
Смена_в_процессе --> Завершение_смены: Смена начата
Завершение_смены --> Ожидание_начала_смены: Введена любая кнопка

state Завершение_смены {
 [*] --> Вывод_счёта

 Вывод_счёта --> Обновление_статусов_офицеров: Счёт выведен
 Обновление_статусов_офицеров --> [*]: Статусы офицеров обновлены
}

Ожидание_начала_смены --> Завершение_программы: Нажата кнопка "N"
Завершение_программы --> [*]: Программа завершена
@enduml
