@startuml
'https://plantuml.com/class-diagram
title Состояния программы

[*] --> Начало_программы
Начало_программы --> Загрузка_данных: Начало программы
Загрузка_данных --> Проверка_сохраненных_данных: Данные загружены
Проверка_сохраненных_данных --> Вывод_меню: Сохраненные данные найдены
Проверка_сохраненных_данных --> Создание_агенства_недвижимости: Сохраненные данные не найдены
Вывод_меню --> Добавление_клиента: Выбран 1ый пункт меню
Вывод_меню --> Добавление_агента: Выбран 2ой пункт меню
Вывод_меню --> Добавление_недвижимости: Выбран 3ий пункт меню
Вывод_меню --> Создание_сделки: Выбран 4ый пункт меню
Вывод_меню --> Сохранение_вывода_информации : Выбран 5ый пункт меню

Добавление_клиента --> Сохранение_состояния: Клиент добавлен
Добавление_агента --> Сохранение_состояния: Агент добавлен
Добавление_недвижимости --> Сохранение_состояния: Недвижимость добавлена
Создание_сделки --> Завершение_программы: Сделка создана
Сохранение_вывода_информации --> Завершение_программы: Информация сохранена
Сохранение_состояния --> Завершение_программы: Состояние сохранено
Создание_агенства_недвижимости --> Завершение_программы: Агенство недвижимости создано
Сохранение_состояния --> Завершение_программы: Состояние сохранено
Завершение_программы --> [*]

state Добавление_клиента {
    [*] --> Ввод_ФИО
    Ввод_ФИО --> Ввод_фамилии_клиента_для_добавления: Имя клиента введено
    Ввод_фамилии_клиента_для_добавления --> Ввод_имени_клиента_для_добавления: Фамилия клиента введена
    Ввод_имени_клиента_для_добавления -->   Создание_клиента: Возраст клиента введен
    Создание_клиента --> Добавление_клиента_в_базу: Клиент создан
    Добавление_клиента_в_базу --> [*]
}

state Добавление_агента {
    [*] --> Ввод_Инициалов_агента
    Ввод_Инициалов_агента --> Ввод_фамилии_агента_для_добавления: Имя агента введено
    Ввод_фамилии_агента_для_добавления --> Ввод_имени_агента_для_добавления: Фамилия агента введена
    Ввод_имени_агента_для_добавления -->   Создание_агента: Возраст агента введен
    Создание_агента --> Добавление_агента_в_базу: Агент создан
    Добавление_агента_в_базу --> [*]
}

state Добавление_недвижимости {
    [*] --> Ввод_информации_о_недвижимости
    Ввод_информации_о_недвижимости -->  Ввод_адреса_недвижимости: Ввод описание недвижимости
    Ввод_адреса_недвижимости -->  Ввод_цены_недвижимости: Введен адрес недвижимости
    Ввод_цены_недвижимости -->  Ввод_количества_комнат: Введена цена недвижимости
    Ввод_количества_комнат --> Ввод_количества_ванных_комнат: Введено количество комнат
    Ввод_количества_ванных_комнат --> Ввод_количества_спален: Введено количество ванных комнат
    Ввод_количества_спален --> [*]: Введено некорректное количество спальных комнат
    Ввод_количества_спален --> Создание_недвижимости: Введено корректное количество спален
}

state Создание_сделки {
    [*] --> Выбор_агента
    Выбор_агента -->  Выбор_недвижимости: Агент выбран
    Выбор_недвижимости --> Выбор_клиента: Недвижимость выбрана
    Выбор_клиента --> Создание_сделки: Клиент выбран
    Создание_сделки --> [*]: Сделка создана
}

state Сохранение_вывода_информации{
    [*] --> Полная_информация_о_сделке
    Полная_информация_о_сделке --> Сделка : Вывод информации о сделке
    Сделка --> [*]

}

state Просмотр_всех_сделок {
    [*] --> Вывод_всех_сделок
    Вывод_всех_сделок --> [*]: Выведены все сделки
}

@enduml